#!/bin/bash
cd "$(dirname "$0")"
cd ./../Gradle-Java-CP/Problemset
mkdir $1
cd $1
gradle init --dsl groovy --package com.algospace --project-name Code --test-framework junit --type java-application --incubating
rm ./app/src/main/java/com/algospace/App.java
cat ./../../Config-Files/Build-Script/run.txt >> ./app/build.gradle
cat ./../../Config-Files/Templates/base.java >> ./app/src/main/java/com/algospace/App.java
gradle build
