#!/bin/bash
cd "$(dirname "$0")"
cd ./../Make-Build-CP/Problemset
mkdir $1
cd $1
cp ../../files/CMakeLists.txt CMakeLists.txt
cp ../../files/code.cpp code.cpp
mkdir bits
cp ../../files/stdc++.h bits/stdc++.h
mkdir build
cd build
cmake -G "Unix Makefiles" -S .. -B .
make
nvim ../code.cpp

