#!/bin/bash
dest="$(dirname "$0")"
codedestination=$dest/../Submit
sub_kt > $codedestination/Code.kt
rm $codedestination/App.kt
cp $codedestination/Code.kt $codedestination/App.kt
rm $codedestination/Code.kt
cat $codedestination/App.kt
